name = "GPUParallel"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
DifferentialEquations = "7.12"
julia = "1.10"
GLMakie = "0.9"
